### ISSUE TITLE
geluidskaart wms laag niet bereikbaar

### ISSUE THREAD

**Issue by milovanderlinden** [RWS-CIV-IRN-TBP/pdokkaart-applicaties#1]
Momenteel is de geluidskaart laag niet zichtbaar.
Ik heb een URL van een van de WMS verzoeken gepakt. Deze geeft een proxy error bij het nationaal georegister.

http://geodata.nationaalgeoregister.nl/rwsgeluidskaarten/wms?LAYERS=geluidskaartennacht&TRANSPARENT=TRUE&FORMAT=image%2Fpng&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A28992&BBOX=237575.36,435474.88,265100.48,463000&WIDTH=256&HEIGHT=256

Kun je even kijken of dit tijdelijk of permanent is?

**Comment by rduivenvoorde** [comment]
tijdelijk probleem, is gefixed
